### ISSUE TITLE
无法登录且闪退

### ISSUE THREAD

**Issue by tychenjiajun** [feeluown/feeluown-xiami#5]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fuo_xiami/ui.py", line 65, in do_verify
    rv = api.login(username, pw_md5digest)
  File "/usr/lib/python3.8/site-packages/fuo_xiami/api.py", line 137, in login
    code, msg, rv = self.request(
  File "/usr/lib/python3.8/site-packages/fuo_xiami/api.py", line 119, in request
    raise XiamiIOError('this API is unavailable anymore')
fuo_xiami.excs.XiamiIOError: [xiami] this API is unavailable anymore
Aborted (core dumped)

**Comment by cosven** [comment]
不好意思，前段时间，虾米 API 有一部分失效了，时间上还没来得及修复。

我争取这两天把程序崩溃的问题给修复，但是登录虾米账户的功能可能得花时间看看了 ~
如果你有兴趣帮忙修复，我也可以随时提供相应的帮助 ~

**Comment by cosven** [comment]
https://github.com/feeluown/feeluown-xiami/commit/cfc56f666560918d2e3fb84d7d609714aba4c63d 程序闪退的问题修复了 ～

无法登录的问题，还需要后续的一些调研 ～

**Comment by cosven** [comment]
https://github.com/feeluown/feeluown-xiami/commit/68448c6e326f36856c441a92423b508c8ea4a80d 修复了无法登录的问题 ～

发了 0.2.2 的版本，你可以通过 pip 来升级 ～如果还有问题，欢迎反馈 ～
